name: TreinaZAP PRD PARA S3

release:
  types: [commit]
  
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          node-version:12
     - run: ls -la
     - run: pwd
